[package]
name = "oracle-sbt"
version = "1.0.0"
authors = ["Robert Zaremba 'https://zaremba.ch/'"]
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]

[dependencies]
uint.workspace = true
near-sdk.workspace = true
serde_json.workspace = true
ed25519-dalek.workspace = true

cost = { path = "../cost" }
sbt = { path = "../sbt" }

[dev-dependencies]
getrandom = { version = "0.2", features = ["js"] }
rand.workspace = true
near-primitives.workspace = true
