[package]
name = "oracle-sbt"
version = "1.0.0"
authors = ["Robert Zaremba 'https://zaremba.ch/'"]
edition = "2021"

[lib]
crate-type = ["cdylib"]


[dependencies]
uint.workspace = true
near-sdk.workspace = true
serde_json.workspace = true
ed25519-dalek.workspace = true

sbt = { path = "../sbt" }

[dev-dependencies]
rand = "^0.7"
