[package]
name = "oracle-sbt"
version = "1.0.0"
authors = ["Robert Zaremba 'https://zaremba.ch/'"]
edition = "2021"

[lib]
crate-type = ["cdylib"]


[dependencies]
near-sdk = "4.1"
uint = { version = "0.9.5", default-features = false }
serde_json = "1.0"
base64 = "^0.21.0"
ed25519 = "1"
