[workspace]
members = [
    "community-sbt",
    "oracle",
    "registry",
    "soulbound",
    "soulbound-class",
    "ubi",
]


# compilation profile for a release target
[profile.release]
codegen-units = 1
# s = optimize for binary size ("z" would additionally turn off loop vectorization)
# 3  all optimiations
opt-level = 3
# link time optimization
lto = true
panic = "abort"
overflow-checks = true
debug = false
debug-assertions = false
rpath = false
