[package]
name = "easy_poll"
version = "0.0.0"
authors = ["Stanislaw Czembor"]
edition = { workspace = true }
repository = { workspace = true }
license = { workspace = true }

[dependencies]
near-sdk.workspace = true
